//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace MVC_Stok_Takip_Sistemi.Models.Entity
{
    public partial class Unit
    {
        public int ID { get; set; }

        [Display(Name = "Unit")] // Label'ý deðiþtirme için ekledik
        public string Unit1 { get; set; }

        public string Description { get; set; }

        public virtual ICollection<Sale> Sales { get; set; }
    }
}

